### ISSUE TITLE
problem with webpack-dev-server. npm start fails.

### ISSUE THREAD

**Issue by darioshanghai** [KleoPetroff/react-webpack-boilerplate#163]
## The problem

npm start fails. There seems to be a problem with webpack-dev-server. 

## Details

```
more ~/dev/react-webpack-boilerplate/npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.10.10
3 info using node@v6.11.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle react-webpack-boilerplate@2.0.0~prestart: react-webpack-boilerplate@2.0.0
6 silly lifecycle react-webpack-boilerplate@2.0.0~prestart: no script for prestart, continuing
7 info lifecycle react-webpack-boilerplate@2.0.0~start: react-webpack-boilerplate@2.0.0
8 verbose lifecycle react-webpack-boilerplate@2.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle react-webpack-boilerplate@2.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/mnt/c/Users
/Dario/Desktop/dev/react-webpack-boilerplate/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/
bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files (x86)/In
tel/iCLS Client:/mnt/c/Program Files/Intel/iCLS Client:/mnt/c/Windows/System32:/mnt/c/Windows:/mnt/c/Windows/System32/wb
em:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components
/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files (x86)/Intel/Intel(R) Mana
gement Engine Components/IPT:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/mnt/c/Program Files/I
ntel/WiFi/bin:/mnt/c/Program Files/Common Files/Intel/WirelessCommon:/mnt/c/Program Files (x86)/Calibre2:/mnt/c/ProgramD
ata/chocolatey/bin:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/nodejs:/mnt/c/Program Files (x86)/Yarn/bin:/mnt/c/U
sers/Dario/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/Dario/AppData/Roaming/npm:/mnt/c/Users/Dario/AppData/Local/Y
arn/bin
10 verbose lifecycle react-webpack-boilerplate@2.0.0~start: CWD: /mnt/c/Users/Dario/Desktop/dev/react-webpack-boilerplat
e
11 silly lifecycle react-webpack-boilerplate@2.0.0~start: Args: [ '-c', 'webpack-dev-server' ]
12 silly lifecycle react-webpack-boilerplate@2.0.0~start: Returned: code: 1  signal: null
13 info lifecycle react-webpack-boilerplate@2.0.0~start: Failed to exec start script
14 verbose stack Error: react-webpack-boilerplate@2.0.0 start: `webpack-dev-server`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:891:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid react-webpack-boilerplate@2.0.0
16 verbose cwd /mnt/c/Users/Dario/Desktop/dev/react-webpack-boilerplate
17 error Linux 4.4.0-43-Microsoft
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v6.11.0
20 error npm  v3.10.10
21 error code ELIFECYCLE
22 error react-webpack-boilerplate@2.0.0 start: `webpack-dev-server`
22 error Exit status 1
23 error Failed at the react-webpack-boilerplate@2.0.0 start script 'webpack-dev-server'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-webpack-boilerplate package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     webpack-dev-server
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-webpack-boilerplate
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-webpack-boilerplate
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by KleoPetroff** [comment]
I think you are using an old version of the boilerplate. Update to version 3.5.3 (or simply pull the latest changes) and try again.

**Comment by darioshanghai** [comment]
I just cloned from the repository today. For a moment I thought I had a
problem with my local node, so I tried updating from LTS to 8.x, but even
that didn't fix it.

**Comment by darioshanghai** [comment]
Not a problem with the boilerplate apparently, but with webpack-dev-server. 

https://github.com/webpack/webpack-dev-server/issues/997

Thanks.
